name: NPM Publish

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.2.3, etc.

permissions:
  contents: read
  id-token: write # Required for npm provenance

jobs:
  publish:
    name: Build, Test & Publish to NPM
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run all quality checks
      run: npm run check-all
      
    - name: Run tests
      run: npm test
      
    - name: Extract version from tag
      id: extract_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"
        
    - name: Update package.json version
      run: |
        npm version ${{ steps.extract_version.outputs.version }} --no-git-tag-version
        echo "Updated package.json to version ${{ steps.extract_version.outputs.version }}"
        
    - name: Verify version update
      run: |
        PACKAGE_VERSION=$(node -p "require('./package.json').version")
        echo "Package.json version: $PACKAGE_VERSION"
        echo "Tag version: ${{ steps.extract_version.outputs.version }}"
        if [ "$PACKAGE_VERSION" != "${{ steps.extract_version.outputs.version }}" ]; then
          echo "Version mismatch!"
          exit 1
        fi
        
    - name: Build project
      run: npm run build
      
    - name: Test CLI after build
      run: ./bin/meteor-upgrade-to-3.js --help
      
    - name: Publish to NPM with provenance
      run: npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create GitHub release summary
      run: |
        echo "## 🚀 Successfully Published to NPM" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Package:** meteor-upgrade-to-3" >> $GITHUB_STEP_SUMMARY
        echo "- **Version:** ${{ steps.extract_version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Registry:** https://www.npmjs.com/package/meteor-upgrade-to-3" >> $GITHUB_STEP_SUMMARY
        echo "- **Install:** \`npm install -g meteor-upgrade-to-3@${{ steps.extract_version.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY